// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://ucjtrmmxrudsrtjmmzip.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InVjanRybW14cnVkc3J0am1temlwIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTcyNjQ4MTMsImV4cCI6MjA3Mjg0MDgxM30.cOlh1cQh77nLhFmHy6SPvMUK7Uhelc6tESjojFWfIWg";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});